---
title: "R packages for meteorological applications"
author: "Jônatan Tatsch"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    fig_width: 6
    highlight: kate
    keep_md: yes
    number_sections: yes
  pdf_document:
    toc: no
---

```{r Chunk0, comment="",prompt=FALSE, echo=FALSE, eval=TRUE, error=TRUE,highlight=TRUE,message=FALSE,warning=FALSE, results='hide'}
rm(list=ls())
Sys.setenv(TZ = 'UTC')
# data manipulation packages
pcks <- c("knitr"#, "knitcitations",
          #"printr"#,
          #"R.utils", "magrittr", "lubridate","stringr", 
          #"plyr", "dplyr", "raster", "lattice",
          #"rasterVis"
          )
invisible(sapply(pcks, require, character.only = TRUE, quietly = TRUE))
rm(pcks)
# configuraçoes knitcitations
#cleanbib()
#cite_options(citation_format = "text",
#            cite.style = "authoryear", 
#            style = "html", 
#            hyperlink = "to.bib")
# configuraçoes knitr
opts_chunk$set(cache = FALSE, fig.path = "figs/")
```

- - -



# Acess to Meteorological data



* [RNCEP](https://cran.r-project.org/web/packages/RNCEP/index.html) Obtain, Organize, and Visualize NCEP Weather Data

* [raincpc](https://cran.r-project.org/web/packages/raincpc/index.html)	Obtain and Analyze Rainfall Data from the Climate Prediction Center

* [worldmet](https://github.com/davidcarslaw/worldmet)	R package for accessing NOAA Integrated Surface Database (ISD) meteorological observations

* [getMet](https://cran.r-project.org/web/packages/getMet/index.html)	Get Meteorological Data for Hydrological Modeling

* [hydroMet](http://r-forge.r-project.org/R/?group_id=2056) Sourcing and Formatting of Meteorological Data for Hydrologic Modeling Applications

* [meteo](https://cran.r-project.org/web/packages/meteo/index.html)	Spatio-Temporal Analysis and Mapping of Meteorological Observations

* [crn](https://cran.r-project.org/web/packages/crn/index.html)	Downloads and Builds datasets for Climate Reference Network

* [FAOSTAT](https://cran.r-project.org/web/packages/FAOSTAT/index.html)	Download Data from the FAOSTAT Database of the Food and Agricultural Organization (FAO) of the United Nations

## Data I/O 

* [cmsaf](https://cran.r-project.org/web/packages/cmsaf/index.html) Tools for CM SAF Netcdf Data

* [readr](https://github.com/hadley/readr) to read tabular data into R

* [rio](https://github.com/hadley/readr) A Swiss-Army Knife for Data I/O 


# Meteorological data analysis and visualization

* [openair](https://cran.r-project.org/web/packages/openair/index.html)	Tools for the Analysis of Air Pollution Data

* [REddyProc](https://cran.r-project.org/web/packages/ClamR/index.html) EddyCovariance data processing and plotting utilities

* [Evapotranspiration](https://cran.r-project.org/web/packages/Evapotranspiration/index.html)	Modelling Actual, Potential and Reference Crop Evapotranspiration]

* [sirad](https://cran.r-project.org/web/packages/sirad/index.html)	Functions for Calculating Daily Solar Radiation and Evapotranspiration

* [insol](https://cran.r-project.org/web/packages/insol/index.html)	Solar Radiation

* [meteogRam](https://cran.r-project.org/web/packages/meteogRam/index.html)	Tools for plotting meteograms

* [meteoForecast](https://cran.r-project.org/web/packages/meteoForecast/index.html)	Numerical Weather Predictions

* [mtsdi](https://cran.r-project.org/web/packages/mtsdi/) Imputação de dados de séries multivariadas; [link](http://www.sciencedirect.com/science/article/pii/S1352231014009145#) para o artigo;

* [rWBclimate](https://cran.r-project.org/web/packages/rWBclimate/index.html)	A package for accessing World Bank climate data

* [RadioSonde](https://cran.r-project.org/web/packages/RadioSonde/index.html) Tools for plotting skew-T diagrams and wind profiles

## Data processing

* [tidyr](https://github.com/hadley/tidyr) Easily tidy data with spread and gather functions.

* [plyr](https://github.com/hadley/plyr) The split-apply-combine strategy for R

* [dplyr](https://github.com/hadley/dplyr) A grammar of data manipulation

* [reshape2](https://github.com/hadley/reshape) reshaping data

* [data.table](https://github.com/Rdatatable/data.table) Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns and a fast file reader (fread)


## Date time

* [hms](https://github.com/rstats-db/hms) A simple class for storing time-of-day values

* [xts](https://cran.r-project.org/web/packages/xts/index.html) eXtensible Time Series

* [lubridate](https://cran.r-project.org/web/packages/lubridate/index.html) Make Dealing with Dates a Little Easier

# Climate tools

* [ClimClass](https://cran.r-project.org/web/packages/ClimClass/index.html)	Climate Classification According to Several Indices

* [climtrends](https://cran.r-project.org/web/packages/climtrends/index.html)	Statistical Methods for Climate Sciences

* [seas](https://cran.r-project.org/web/packages/seas/index.html) Seasonal analysis and graphics, especially for climatology

* [clifro](https://cran.r-project.org/web/packages/clifro/index.html)	Easily Download and Visualise Climate Data from CliFlo

* [climwin](https://cran.r-project.org/web/packages/climwin/index.html)	Climate Window Analysis

* [comclim](https://cran.r-project.org/web/packages/comclim/index.html)	Community climate statistics

* [dcv](https://cran.r-project.org/web/packages/dcv/index.html)	Conventional Cross-validation statistics for climate-growth model

* [HiClimR](https://cran.r-project.org/web/packages/HiClimR/index.html)	Hierarchical Climate Regionalization

* [qmap](https://cran.r-project.org/web/packages/qmap/index.html)	Statistical transformations for post-processing climate model output

* [SCI](https://cran.r-project.org/web/packages/SCI/index.html)	Standardized Climate Indices such as SPI, SRI or SPEI

* [SPEI](https://cran.r-project.org/web/packages/SPEI/index.html)	Calculation of the Standardised Precipitation-Evapotranspiration Index

* [HelpersMG](https://cran.r-project.org/web/packages/HelpersMG/index.html)	Tools for Earth Meteorological Analysis

* [TSA](https://cran.r-project.org/web/packages/TSA/index.html)	Time Series Analysis

* [ClamR](https://cran.r-project.org/web/packages/ClamR/index.html) Time Series Modeling for Climate Change Proxies

* [timsac](https://cran.r-project.org/web/packages/timsac/index.html)	Time Series Analysis and Control package

# Hydrometeorology

* [topmodel](https://cran.r-project.org/web/packages/topmodel/index.html)	Implementation of the hydrological model TOPMODEL in R

* [dynatopmodel](https://cran.r-project.org/web/packages/dynatopmodel/index.html)	Implementation of the Dynamic TOPMODEL hydrological model

* [waterData](https://cran.r-project.org/web/packages/waterData/index.html)	An R Package for Retrieval, Analysis, and Anomaly Calculation of Daily Hydrologic Time Series Data

* [EcoHydRology](https://cran.r-project.org/web/packages/EcoHydRology/index.html)	A community modeling foundation for Eco-Hydrology

* [hddtools](https://cran.r-project.org/web/packages/hddtools/index.html)	Hydrological Data Discovery Tools

* [hydroApps](https://cran.r-project.org/web/packages/hydroApps/index.html)	Tools and models for hydrological applications

* [hydrogeo](https://cran.r-project.org/web/packages/hydrogeo/index.html)	Groundwater data presentation and interpretation

* [hydroGOF](https://cran.r-project.org/web/packages/hydroGOF/index.html)	Goodness-of-fit functions for comparison of simulated and observed hydrological time series

* [HydroMe](https://cran.r-project.org/web/packages/HydroMe/index.html)	R codes for estimating water retention and infiltration model parameters using experimental data

* [hydrostats](https://cran.r-project.org/web/packages/hydrostats/index.html)	Hydrologic Indices for Daily Time Series Data

* [hydroTSM](https://cran.r-project.org/web/packages/hydroTSM/index.html)	Time series management, analysis and interpolation for hydrological modelling

* [precintcon](https://cran.r-project.org/web/packages/precintcon/index.html)	Precipitation Intensity, Concentration and Anomaly Analysis

* [RGENERATEPREC](https://cran.r-project.org/web/packages/RGENERATEPREC/index.html)	Tools To Generate Daily-Precipitation Time Series

* [water](https://cran.r-project.org/web/packages/water/index.html)	Actual Evapotranspiration with Energy Balance Models

* [kwb.hantush](https://cran.r-project.org/web/packages/kwb.hantush/index.html)	Calculation of Groundwater Mounding Beneath an Infiltration Basin

* [modiscloud](https://cran.r-project.org/web/packages/modiscloud/index.html)	R tools for processing Level 2 Cloud Mask products from MODIS

* [MODISTools](https://cran.r-project.org/web/packages/MODISTools/index.html)	MODIS Subsetting Tools

* [radar](https://cran.r-project.org/web/packages/radar/index.html)	Fundamental Formulas for Radar








